#!/usr/bin/env python3
"""API digest: the exported surface of a directory tree, one file per source
directory, so a session greps signatures instead of reading whole components.
Mechanical (regex), no model, runs in a second.

  api-digest.py --out <dir> [roots...]     (default roots: app components lib models)

Per source file: each exported function/const/type/interface with its
signature line (up to the opening brace), the JSDoc line above it, and for
React components the props block. A file's entry is capped so one huge
component cannot dominate.
"""
import os, re, sys
args = sys.argv[1:]
out = args[args.index("--out") + 1] if "--out" in args else "api-digest"
roots = [a for i, a in enumerate(args) if a != "--out" and (i == 0 or args[i - 1] != "--out")] or ["app", "components", "lib", "models"]
SRC = re.compile(r"\.(tsx?|mjs|js)$")
EXP = re.compile(r"^export\s+(default\s+)?(async\s+)?(function|const|let|class|type|interface|enum)\s+([A-Za-z0-9_$]+)")
SKIP_DIRS = {"node_modules", ".next", "generated", "client", "__tests__"}
os.makedirs(out, exist_ok=True)
index = []
for root in roots:
    for dp, dn, fn in os.walk(root):
        dn[:] = [d for d in dn if d not in SKIP_DIRS]
        files = sorted(f for f in fn if SRC.search(f) and not f.endswith((".test.ts", ".test.tsx", ".d.ts")))
        if not files: continue
        entries = []
        for f in files:
            p = os.path.join(dp, f)
            try: lines = open(p, errors="replace").read().split("\n")
            except Exception: continue
            items = []
            for i, ln in enumerate(lines):
                m = EXP.match(ln)
                if not m: continue
                doc = ""
                j = i - 1
                while j >= 0 and lines[j].strip().startswith(("*", "/**", "//")):
                    if lines[j].strip().startswith("/**") or lines[j].strip().startswith("//"): doc = lines[j].strip().lstrip("/* ").rstrip("*/ ")[:160]; break
                    j -= 1
                sig = ln.strip()
                # extend the signature to the opening brace / arrow, max 6 lines
                k = i
                while not re.search(r"[{=]\s*$|=>\s*\{?$|\)\s*\{$|;\s*$", sig) and k + 1 < len(lines) and k - i < 6:
                    k += 1; sig += " " + lines[k].strip()
                sig = re.sub(r"\s+", " ", sig)[:400]
                props = ""
                if m.group(3) == "function" and f.endswith(".tsx") and "}: {" in sig:
                    # props block: from `}: {` to the line `}) {`
                    blk = []; k2 = i + 1
                    while k2 < len(lines) and not lines[k2].startswith("}) {") and len(blk) < 40:
                        s = lines[k2].strip()
                        if s and not s.startswith(("/**", "*", "//")): blk.append(s)
                        k2 += 1
                    props = " · ".join(blk)[:900]
                items.append(f"- L{i+1} `{sig}`" + (f"\n  props: {props}" if props else "") + (f"\n  — {doc}" if doc else ""))
            if items:
                entries.append(f"### {p} ({len(lines)} lines)\n" + "\n".join(items[:60]))
        if entries:
            name = dp.replace("/", "__") + ".md"
            open(os.path.join(out, name), "w").write(f"# API digest — {dp}\n\nSignatures only; open a file to edit it, not to learn its API. Regenerated by the driver before every session.\n\n" + "\n\n".join(entries) + "\n")
            index.append((dp, name, len(entries)))
open(os.path.join(out, "INDEX.md"), "w").write("# API digest index\n\n" + "\n".join(f"- `{n}` — {d} ({c} files)" for d, n, c in index) + "\n")
print(f"{len(index)} directories → {out}")
