#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Tour complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the lanes tour. Live state from this checkout at every stage — the
# wizard shows what Bite is doing, it never changes anything.
#   scripts/wayfinder-autopilot/lanes-tour.sh [<map>]
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ROOT="$(git rev-parse --show-toplevel)"; cd "$ROOT"
MAP="${1:-$(ls -t docs/wayfinder-reports 2>/dev/null | grep -E '^[0-9]+$' | head -1)}"
LANES_DIR="$(dirname "$ROOT")/$(basename "$ROOT")-lanes"
REPO="$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || echo '?')"
BASE="$(git rev-parse --abbrev-ref HEAD)"
CFG=".claude/wayfinder-autopilot/config.sh"
show() { printf '%s' "$DIM"; "$@" 2>&1 | sed 's/^/    /' | head -${LINES_MAX:-12}; printf '%s' "$RESET"; }

banner "Bite lanes — how a ticket travels (map #$MAP)"

stage "The shape: checkout, lanes, integration branch"
say "This checkout ($ROOT) is on the integration branch: $BASE."
say "Bite never writes here while a ticket is open. Each ticket gets a lane:"
say "a git worktree in $LANES_DIR/<map>-<ticket> on branch wf/<map>-<ticket>."
note "Worktrees right now:"
show git worktree list
note "Lane folders right now (none = nothing in flight):"
show ls -1 "$LANES_DIR"
say "A lane shares node_modules, .env and .impeccable/live with this checkout by symlink;"
say "everything else (.next, captures) is its own. Sequential: one lane runs at a time."
pause

stage "Watching a lane open"
say "The driver prints one line when it creates a lane, before the session starts:"
note '    lane /home/…/Wes-doc-lanes/353-361 on wf/353-361 (from codex/post-login-ux-implementation)'
say "Look for it in the feed (last lines shown here):"
show tail -n 8 "docs/wayfinder-reports/$MAP/detached.out"
say "Inside the lane, git shows the ticket branch and only the session's own changes:"
L="$(ls -d "$LANES_DIR/$MAP-"* 2>/dev/null | head -1)"
if [[ -n "$L" ]]; then show git -C "$L" status -sb; else note "(no lane open for map #$MAP at the moment)"; fi
pause

stage "Work in flight: the draft PR"
say "After every session the lane branch is pushed. The first push opens a DRAFT PR"
say "wf/<map>-<ticket> → $BASE, so anyone can read the diff while the ticket is open."
note "Open lane PRs on $REPO:"
show gh pr list --repo "$REPO" --state open --limit 50 --json number,title,isDraft,headRefName --jq ".[] | select(.headRefName|startswith(\"wf/$MAP-\")) | \"#\\(.number)  \\(if .isDraft then \"draft\" else \"ready\" end)  \\(.headRefName)  \\(.title)\""
say "The PR body names the report and hand-off: docs/wayfinder-reports/<map>/<ticket>.md and .handoff.md,"
say "both committed on the lane branch — that is where the driver reads the phase from."
if confirm "Open the newest lane PR in the browser?"; then
  PR="$(gh pr list --repo "$REPO" --state open --limit 50 --json url,headRefName --jq "[.[] | select(.headRefName|startswith(\"wf/$MAP-\"))][0].url // empty" 2>/dev/null || true)"
  [[ -n "$PR" ]] && open_url "$PR" || note "(no open lane PR)"
fi
pause

stage "Landing: what happens when a ticket closes at the bar"
say "The session closes the issue (the token-guard hook refuses that below the bar)."
say "Then the driver, in this checkout:"
step "marks the PR ready (gh pr ready)"
step "git merge --no-ff wf/<map>-<ticket>   → one merge commit 'land(#N): <title> (PR #M)'"
step "git push origin $BASE                  → GitHub records PR #M as merged"
step "removes the lane folder and deletes the local branch"
note "Landed tickets so far (merge commits on $BASE):"
show git log --merges --oneline -n 6 --grep='^land('
say "If the merge conflicts with uncommitted changes here, nothing is forced: the PR stays open,"
say "the lane is kept, and the feed says 'could not land'. Stage 8 shows landing by hand."
pause

stage "Working beside Bite: the three rules"
step "Your checkout is yours. Edit, commit, run the dev server on another port — Bite doesn't touch it mid-ticket."
step "A lane is the session's. Don't edit files under $LANES_DIR; if you must take a ticket over, stop Bite first (stage 7)."
step "The merge at close writes to this checkout. Keep unrelated edits committed so the land never conflicts with them."
say "Reading what a session is doing is always safe:"
note "  tail -f docs/wayfinder-reports/$MAP/detached.out"
note "  git -C $LANES_DIR/$MAP-<ticket> log --oneline -5"
note "  gh pr view <PR> --repo $REPO"
pause

stage "Review mode: a human gate before landing"
say "In $CFG:"
show grep -nE '^LANE_(MODE|MERGE)=' "$CFG"
say "LANE_MERGE=auto  → the driver lands each closed ticket at once (today's setting)."
say "LANE_MERGE=review → the PR is marked ready and LEFT OPEN. You review and merge on GitHub."
say "                    The frontier holds back any ticket whose blocker's PR is still open,"
say "                    so nothing is built on unreviewed code. Then: git pull here before the next run."
say "Switching: edit the line, then restart the driver at a ticket boundary (it reads config once)."
pause

stage "Stop and resume"
say "scripts/wayfinder-autopilot/stop.sh $MAP"
step "stops the driver, then the running session cleanly"
step "commits the lane's tree as WIP on wf/<map>-<ticket> and pushes it"
step "posts 'Autopilot: continue —' on the ticket and releases the claim"
say "scripts/wayfinder-autopilot/run.sh $MAP --detach"
step "the ticket is back on the frontier; its lane and branch are reused, and the session"
step "continues from the hand-off file committed in the lane."
note "Is Bite running now?"
show pgrep -af "wayfinder-autopilot/run.sh $MAP"
pause

stage "Landing by hand (only when the feed said 'could not land')"
say "From this checkout, on $BASE, with your own changes committed:"
note "  git merge --no-ff -m 'land(#N): <title> (PR #M)' wf/$MAP-N"
note "  git push origin $BASE"
note "  git worktree remove $LANES_DIR/$MAP-N && git branch -d wf/$MAP-N"
say "GitHub marks PR #M merged as soon as its head is on $BASE. If a stale lane is left behind"
say "after a crash, the same two last lines clean it up; 'git worktree prune' clears dangling entries."
pause

finish
