/** A6.2: an inbound email whose invoice IS the email body (no attachment) used to vanish. This
 * module decides whether a body looks like a billing document (cheap keyword heuristic — no LLM,
 * per the roadmap's ~1-call/doc budget) and renders its text content into a small single-font PDF
 * so it can ride the exact same ingestion pipeline as an attached file. Pure — no Prisma, no IO —
 * so it is unit-testable; models/inbound-email.ts does the ingesting.
 *
 * The PDF is generated by hand (no renderer dependency exists in this app, and puppeteer-class
 * ones are not worth their weight here): one embedded base-14 Helvetica font, text lines only.
 * Layout/styling is deliberately lost — the extraction pipeline reads text, not design. */

const INVOICE_HINTS = [
  "invoice", "receipt", "statement", "remittance", "amount due", "total due", "balance due",
  "payment due", "order confirmation", "your order", "subtotal", "vat", "tax invoice", "bill",
]
const AMOUNT_PATTERN = /(?:[$€£]\s?\d[\d,.]*|\d[\d,.]*\s?(?:usd|eur|gbp|zar|aud|cad)\b)/i

/** True when the subject/body plausibly carry a billing document: at least one billing keyword
 * AND at least one money-looking amount. Both required — "see you at dinner, the bill was fun"
 * has a keyword but no amount; a bare "$5" in a signature has an amount but no keyword. */
export function looksInvoiceLike(subject: string | null | undefined, bodyText: string | null | undefined): boolean {
  const haystack = `${subject ?? ""}\n${bodyText ?? ""}`.toLowerCase()
  if (!haystack.trim()) return false
  return INVOICE_HINTS.some((hint) => haystack.includes(hint)) && AMOUNT_PATTERN.test(haystack)
}

/** Plain text out of an HTML body: tags stripped, block elements to newlines, entities decoded
 * (the common ones — this feeds an extractor, not a browser). */
export function htmlToText(html: string): string {
  return html
    .replace(/<(?:style|script)[\s\S]*?<\/(?:style|script)>/gi, "")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/(?:p|div|tr|li|h[1-6]|table|section|header|footer)>/gi, "\n")
    .replace(/<td[^>]*>/gi, "\t")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;|&apos;/gi, "'")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim()
}

const PAGE_WIDTH = 612 // US Letter, points
const PAGE_HEIGHT = 792
const MARGIN = 54
const FONT_SIZE = 10
const LINE_HEIGHT = 14
const MAX_CHARS_PER_LINE = 95
const LINES_PER_PAGE = Math.floor((PAGE_HEIGHT - 2 * MARGIN) / LINE_HEIGHT)
const MAX_PAGES = 20

function escapePdfText(line: string): string {
  // PDF string syntax + WinAnsi-ish coercion: parens/backslash escaped, anything outside
  // Latin-1 replaced (a lost glyph beats a corrupt content stream).
  return line
    .replace(/[\\()]/g, (ch) => `\\${ch}`)
    .replace(/[^\x20-\x7e\xa0-\xff]/g, "?")
}

function wrapLine(line: string): string[] {
  if (line.length <= MAX_CHARS_PER_LINE) return [line]
  const words = line.split(" ")
  const wrapped: string[] = []
  let current = ""
  for (const word of words) {
    if (current && current.length + 1 + word.length > MAX_CHARS_PER_LINE) {
      wrapped.push(current)
      current = word
    } else {
      current = current ? `${current} ${word}` : word
    }
    while (current.length > MAX_CHARS_PER_LINE) {
      wrapped.push(current.slice(0, MAX_CHARS_PER_LINE))
      current = current.slice(MAX_CHARS_PER_LINE)
    }
  }
  if (current) wrapped.push(current)
  return wrapped
}

/** Renders header lines + body text into a valid single-font PDF buffer. */
export function renderEmailBodyPdf(input: { subject: string | null; from: string; bodyText: string }): Buffer {
  const headerLines = [
    `From: ${input.from}`,
    ...(input.subject ? [`Subject: ${input.subject}`] : []),
    "(rendered from email body by DocuBite)",
    "",
  ]
  const lines = [...headerLines, ...input.bodyText.split("\n")].flatMap(wrapLine)

  const pages: string[][] = []
  for (let i = 0; i < lines.length && pages.length < MAX_PAGES; i += LINES_PER_PAGE) {
    pages.push(lines.slice(i, i + LINES_PER_PAGE))
  }
  if (!pages.length) pages.push([""])

  // Object layout: 1 catalog, 2 pages-tree, 3 font, then per page: page object + content stream.
  const objects: string[] = []
  const pageObjectIds = pages.map((_, index) => 4 + index * 2)
  objects.push(`1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n`)
  objects.push(`2 0 obj\n<< /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pages.length} >>\nendobj\n`)
  objects.push(`3 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj\n`)

  pages.forEach((pageLines, index) => {
    const pageId = pageObjectIds[index]
    const contentId = pageId + 1
    const textOps = pageLines
      .map((line, lineIndex) => `1 0 0 1 ${MARGIN} ${PAGE_HEIGHT - MARGIN - lineIndex * LINE_HEIGHT} Tm (${escapePdfText(line)}) Tj`)
      .join("\n")
    const stream = `BT\n/F1 ${FONT_SIZE} Tf\n${textOps}\nET`
    objects.push(`${pageId} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentId} 0 R >>\nendobj\n`)
    objects.push(`${contentId} 0 obj\n<< /Length ${Buffer.byteLength(stream, "latin1")} >>\nstream\n${stream}\nendstream\nendobj\n`)
  })

  const header = "%PDF-1.4\n"
  let offset = Buffer.byteLength(header, "latin1")
  const offsets: number[] = []
  for (const object of objects) {
    offsets.push(offset)
    offset += Buffer.byteLength(object, "latin1")
  }
  const xrefStart = offset
  const xref = [
    `xref\n0 ${objects.length + 1}\n`,
    "0000000000 65535 f \n",
    ...offsets.map((position) => `${String(position).padStart(10, "0")} 00000 n \n`),
  ].join("")
  const trailer = `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`

  return Buffer.from(header + objects.join("") + xref + trailer, "latin1")
}
