// Autopilot helper (#251): append the Decisions-so-far line and graduate the fog patch on map #226.
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
const body = execFileSync('gh', ['issue', 'view', '226', '--json', 'body', '-q', '.body'], { encoding: 'utf8' })
const line = `- [Build the Payments destination: Bill Pay and Payment Batches on the queue shell, with payer accounts, terms, discounts and payment records (#251)](https://github.com/petrose99/Wes-doc/issues/251) (task, shipped \`20cd468\`, autopilot): one rail item **Payments** → \`/payments/bill-pay\` and \`/payments/batches\` on the #225 shell; Bill Pay lists Approved unpaid invoices with terms ("2/10 net 30"), the open discount window's purple countdown, Amount to pay (discounted over struck due, inline 0 < amount ≤ due), Pay From and the *Open invoices by age* band, un-batchable rows visible with the reason; Create batch is a real Dialog that becomes the receipt (one batch per payer account × currency, in one transaction); Payment Batches runs Pending approval → Approved → Paid / Rejected-with-reason with the 60% pane (facts strip, supplier-grouped lines, remittance advices, Audit), sticky Reject… · Approve, Download (a fact, \`exportedAt\`) · Mark batch as paid…, Remove payment records… with a reason; paid state is derived on every invoice row per ADR 0001 ("Paid (recorded)"); Settings › Payments holds payer accounts and supplier terms/discount/bank details; additive migration; "Prepare payment run" left the Invoices bulk bar. New UI scores: critique 27 → **34/40** (all ≥ 3), evaluate 68 → **85/100** (all ≤ 1, Clean), in-page detector at the app-wide residual 5 on every surface at 1440/390. Decisions surfaced: [#276](https://github.com/petrose99/Wes-doc/issues/276) (are un-batchable rows selectable), [#278](https://github.com/petrose99/Wes-doc/issues/278) (single-owner speed bump); fog graduated: [#277](https://github.com/petrose99/Wes-doc/issues/277); #248 unblocked.`
const fogOld = `- Paying an approved Expense claim — whether it becomes a Bill Pay row for the Claimant (a Payer account paying a person, not a supplier) and so a line in a Payment batch: chartable once #251 ships; until then an approved claim ends at Approved and the reimbursement happens outside DocuBite.\n`
if (!body.includes(fogOld)) throw new Error('fog line not found')
const anchor = '\n## Not yet specified'
if (!body.includes(anchor)) throw new Error('anchor not found')
let next = body.replace(fogOld, '')
next = next.replace(anchor, `\n${line}\n${anchor}`)
// #229's own fog lines sharpen: the payments-approval-flow patch now names #278 as the single-owner slice already taken.
next = next.replace(`- A payments approval flow (who may approve a batch beyond "any owner", amount thresholds, a second signature) and a payments role for members: chartable once Approval Flows (#253) and Users (#254) ship; until then #229's member-submits / owner-decides rule stands.`,
  `- A payments approval flow (who may approve a batch beyond "any owner", amount thresholds, a second signature) and a payments role for members: chartable once Approval Flows (#253) and Users (#254) ship; until then #229's member-submits / owner-decides rule stands. The one-owner case (labelling self-approval vs a speed bump) is already #278.`)
writeFileSync('/tmp/scratch229/map226-body.md', next)
execFileSync('gh', ['issue', 'edit', '226', '--body-file', '/tmp/scratch229/map226-body.md'], { encoding: 'utf8' })
console.log('map updated; fog line removed:', !next.includes(fogOld), '; decisions line added:', next.includes('(#251)](https://github.com/petrose99/Wes-doc/issues/251) (task, shipped'))
