import { BiteMark } from "@/components/marketing/logo"
import { ArrowRight, BadgeCheck, BarChart3, BellRing, BookOpenCheck, Bot, Building2, Check, ChevronRight, CircleCheck, FileCheck2, FileText, Globe2, Layers3, LineChart, LockKeyhole, Mail, ShieldCheck, Sparkles, Split, TimerReset, UsersRound, WandSparkles, Zap } from "lucide-react"
import Link from "next/link"
import { LandingSwitcher } from "./landing-switcher"

type Variant = "a" | "b" | "c"

const Button = ({ children, secondary = false }: { children: React.ReactNode; secondary?: boolean }) => (
  <Link href={secondary ? "/demo" : "/signup"} className={secondary ? "inline-flex h-11 items-center justify-center gap-2 rounded-lg border border-current px-5 text-sm font-semibold transition hover:bg-black/5" : "inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-emerald-500 px-5 text-sm font-bold text-slate-950 shadow-lg shadow-emerald-500/20 transition hover:bg-emerald-400"}>
    {children} {!secondary && <ArrowRight className="h-4 w-4" />}
  </Link>
)

function Stat({ value, label, dark = false }: { value: string; label: string; dark?: boolean }) {
  return <div className={`border-l pl-4 ${dark ? "border-slate-700" : "border-slate-200"}`}><div className={`font-display text-2xl font-bold tracking-tight ${dark ? "text-white" : "text-slate-950"}`}>{value}</div><div className={`mt-1 text-xs leading-5 ${dark ? "text-slate-400" : "text-slate-500"}`}>{label}</div></div>
}

function WorkflowMock() {
  const docs = [
    ["Travelbird Ltd", "£4,280.00", "Ready to post", "emerald"],
    ["Northern Office", "£862.75", "Needs approval", "amber"],
    ["Landmark Cloud", "£1,980.00", "Policy checked", "blue"],
  ]
  const statusTone: Record<string, string> = { emerald: "text-emerald-300", amber: "text-amber-300", blue: "text-blue-300" }
  return <div className="overflow-hidden rounded-xl border border-slate-700 bg-[#111c2a] text-slate-200 shadow-2xl shadow-slate-950/50">
    <div className="flex items-center justify-between border-b border-slate-700 px-4 py-3"><div className="flex items-center gap-2 text-xs font-semibold"><BiteMark className="h-4 w-4" /><span>March close</span></div><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] font-bold text-emerald-300">18:42 saved</span></div>
    <div className="grid grid-cols-[112px_1fr] sm:grid-cols-[150px_1fr]">
      <aside className="border-r border-slate-700 p-3 text-[11px] text-slate-400"><p className="mb-3 px-2 text-[9px] font-bold uppercase tracking-widest text-slate-500">Workspace</p>{["Overview", "Bills", "Approvals", "Policies", "Close"].map((name, i) => <div key={name} className={`mb-1 flex items-center justify-between rounded-md px-2 py-2 ${i === 1 ? "bg-white/10 text-white" : ""}`}><span>{name}</span>{i === 1 && <b className="text-emerald-300">8</b>}</div>)}</aside>
      <div className="p-4"><div className="mb-4 flex flex-wrap items-end justify-between gap-2"><div><p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Today&apos;s work</p><h3 className="mt-1 text-base font-bold text-white">Bills that can move</h3></div><button className="rounded-md bg-emerald-400 px-2.5 py-1.5 text-[10px] font-bold text-slate-950">Review queue</button></div>
        <div className="space-y-2">{docs.map(([supplier, total, status, colour]) => <div key={supplier} className="grid grid-cols-[1fr_auto] items-center gap-2 rounded-lg border border-slate-700 bg-slate-800/70 p-3"><div className="min-w-0"><p className="truncate text-xs font-semibold text-white">{supplier}</p><p className="mt-1 text-[10px] text-slate-400">Invoice · data captured · 2 matching rules</p></div><div className="text-right"><p className="text-xs font-bold text-white">{total}</p><p className={`mt-1 text-[10px] font-semibold ${statusTone[colour]}`}>{status}</p></div></div>)}</div>
      </div>
    </div>
  </div>
}

function VariantA() {
  return <div className="min-h-screen overflow-hidden bg-[#08131f] text-white">
    <main>
      <section className="relative border-b border-slate-800"><div className="absolute inset-0 opacity-40" style={{ backgroundImage: "linear-gradient(rgba(255,255,255,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.045) 1px,transparent 1px)", backgroundSize: "56px 56px", maskImage: "linear-gradient(to bottom, black, transparent)" }} />
        <div className="relative mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-16 lg:grid-cols-[1.03fr_.97fr] lg:items-center lg:pt-24"><div><p className="inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs font-bold text-emerald-300"><Sparkles className="h-3.5 w-3.5" /> AI that does the work, not just the reading</p><h1 className="mt-6 max-w-3xl font-display text-5xl font-extrabold leading-[.98] tracking-[-.055em] text-white sm:text-7xl">Close the books. <span className="text-emerald-400">Not your day.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">DocuBite turns every incoming bill into a controlled, audit-ready accounting event. Capture, decide, approve and post in one calm operating system.</p><div className="mt-9 flex flex-wrap gap-3"><Button>Start free for 14 days</Button><Button secondary>See it in action</Button></div><p className="mt-4 text-xs text-slate-500">No card. Your bank stays your bank.</p></div><WorkflowMock /></div>
      </section>
      <section className="mx-auto grid max-w-7xl grid-cols-2 gap-7 px-5 py-10 sm:grid-cols-4"><Stat dark value="92%" label="of bills move without a touch"/><Stat dark value="1 place" label="for intake to audit trail"/><Stat dark value="0 gaps" label="between approval and posting"/><Stat dark value="24/7" label="document intake, any format"/></section>
      <section id="product" className="border-y border-slate-800 bg-[#0d1927]"><div className="mx-auto max-w-7xl px-5 py-24"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-400">The AP control loop</p><h2 className="mt-4 font-display text-4xl font-bold tracking-tight sm:text-5xl">One straight line from inbox to ledger.</h2><p className="mt-5 text-lg leading-8 text-slate-400">Every action is accounted for. Every exception has an owner. The result is speed you can explain.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-xl border border-slate-700 bg-slate-700 md:grid-cols-4">{[[Mail,"Capture","Email, upload, API or phone photo—into one queue."],[Bot,"Understand","AI extracts the line items, tax and context that matter."],[ShieldCheck,"Control","Rules flag duplicates, missing evidence and risky changes."],[BookOpenCheck,"Post","Approved work lands cleanly in your books."]].map(([Icon,title,copy], i) => { const IconComponent = Icon as typeof Mail; return <article key={title as string} className="bg-[#0d1927] p-7"><span className="text-xs font-bold text-slate-500">0{i + 1}</span><IconComponent className="mt-8 h-6 w-6 text-emerald-400" /><h3 className="mt-5 text-lg font-bold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{copy as string}</p></article>})}</div></div></section>
      <section id="security" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-2"><div className="rounded-2xl bg-emerald-400 p-8 text-slate-950 sm:p-11"><ShieldCheck className="h-9 w-9"/><h2 className="mt-16 font-display text-4xl font-bold tracking-tight">Control is built into the flow.</h2><p className="mt-5 max-w-md text-lg leading-8 text-emerald-950/75">Duplicate detection, approvals, document provenance and a complete audit trail are the default—not add-ons.</p><a className="mt-10 inline-flex items-center gap-2 text-sm font-bold" href="#resources">Explore controls <ArrowRight className="h-4 w-4" /></a></div><div className="flex flex-col justify-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-400">Built for accountable teams</p><h2 className="mt-4 font-display text-4xl font-bold tracking-tight">The speed finance wants. The evidence everyone needs.</h2>{["Permissioned approvals with clear escalation", "Checks that learn from your real supplier history", "Evidence linked back to the original document"].map((item) => <p key={item} className="mt-6 flex gap-3 text-slate-300"><CircleCheck className="h-5 w-5 shrink-0 text-emerald-400" />{item}</p>)}</div></section>
      <section id="resources" className="border-t border-slate-800 px-5 py-24 text-center"><p className="text-sm font-semibold text-emerald-400">A better close starts with the next bill.</p><h2 className="mx-auto mt-4 max-w-3xl font-display text-5xl font-bold tracking-tight">Give your finance team their time back.</h2><div className="mt-8"><Button>Start your free trial</Button></div></section>
    </main></div>
}

function PaperDocument() { return <div className="relative mx-auto max-w-md rotate-[-2deg] rounded-sm border border-stone-200 bg-white p-6 shadow-[12px_16px_0_#e7dfd1,25px_30px_0_#f0eadf]"><div className="flex items-center justify-between"><div className="h-7 w-24 rounded bg-stone-900"/><span className="text-xs text-stone-400">INVOICE</span></div><div className="mt-9 space-y-2">{["Linden & Co. / INV–002481","Subtotal · £1,818.00","VAT · £363.60","TOTAL · £2,181.60"].map((row,i) => <div key={row} className={`flex justify-between border-b pb-2 text-xs ${i === 3 ? "border-emerald-500 font-bold text-stone-900" : "border-stone-100 text-stone-500"}`}><span>{row.split(" · ")[0]}</span><span>{row.split(" · ")[1] ?? ""}</span></div>)}</div><div className="mt-7 flex items-center gap-2 rounded bg-emerald-50 p-3 text-xs font-semibold text-emerald-800"><BadgeCheck className="h-4 w-4"/> Extracted, verified, policy checked</div></div> }

function VariantB() { return <div className="min-h-screen bg-[#fbf8f2] text-stone-900">
  <main><section className="border-y border-stone-200"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Finance, with its receipts attached</p><h1 className="mt-6 max-w-3xl font-display text-5xl font-extrabold leading-[1] tracking-[-.055em] sm:text-7xl">Every number should know <em className="font-medium text-emerald-700">where it came from.</em></h1><p className="mt-7 max-w-xl text-lg leading-8 text-stone-600">DocuBite makes the operational work behind each accounting entry visible, reliable and surprisingly easy to move forward.</p><div className="mt-9 flex flex-wrap gap-3"><Button>See your workflow</Button><Button secondary>Talk to a specialist</Button></div></div><PaperDocument /></div></section>
  <section id="solutions" className="mx-auto max-w-7xl px-5 py-24"><div className="grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-semibold text-emerald-700">The problem isn&apos;t documents. It&apos;s the chasing.</p><h2 className="mt-4 font-display text-4xl font-bold tracking-tight">The month-end story, rewritten.</h2></div><p className="text-lg leading-8 text-stone-600">Your team should not have to translate between email threads, spreadsheets, approval pings and your ledger. DocuBite gives every bill one durable, shared story—from arrival to reconciliation.</p></div><div className="mt-16 grid gap-10 md:grid-cols-3">{[["01","Arrives","A bill comes in from anywhere. Its source and original file never get lost."],["02","Understood","Data is extracted, compared to history and given the business context needed to decide."],["03","Accounted for","The right person approves. The right system updates. The proof remains attached."]].map(([n,title,copy]) => <article key={n} className="border-t-2 border-stone-900 pt-5"><span className="font-display text-2xl font-bold text-emerald-700">{n}</span><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-stone-600">{copy}</p></article>)}</div></section>
  <section id="product" className="bg-stone-900 px-5 py-24 text-white"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-8"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Not another black box</p><h2 className="mt-4 max-w-xl font-display text-4xl font-bold tracking-tight">Ask a question. Find the receipt. Understand the decision.</h2></div><p className="max-w-sm text-sm leading-6 text-stone-400">A modern document workspace where details, controls and collaboration live beside the work.</p></div><div className="mt-12 grid overflow-hidden rounded-xl border border-stone-700 bg-stone-800 lg:grid-cols-[1fr_.65fr]"><div className="p-7 sm:p-10"><div className="flex items-center gap-3"><FileText className="h-5 w-5 text-emerald-400"/><div><p className="font-semibold">Linden & Co. invoice</p><p className="text-xs text-stone-400">Received from accounts@linden.co · 4 minutes ago</p></div></div><div className="mt-10 grid gap-4 sm:grid-cols-2">{[["Amount","£2,181.60"],["Coding","Software subscriptions"],["Reviewer","Priya Shah"],["Evidence","3 checks passed"]].map(([l,v]) => <div key={l} className="rounded-lg bg-stone-900 p-4"><p className="text-xs text-stone-500">{l}</p><p className="mt-2 text-sm font-semibold">{v}</p></div>)}</div><div className="mt-5 rounded-lg border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm text-emerald-100">“This invoice matches the purchase order and is within the supplier&apos;s normal range.”</div></div><aside className="border-t border-stone-700 bg-[#18271f] p-7 lg:border-l lg:border-t-0"><p className="text-xs font-bold uppercase tracking-widest text-emerald-400">Activity</p>{["AI read 14 fields", "PO-448 matched", "Policy check passed", "Priya requested approval"].map((item) => <div key={item} className="mt-5 flex items-start gap-3 text-sm text-stone-300"><span className="mt-1 h-2 w-2 rounded-full bg-emerald-400"/>{item}</div>)}</aside></div></div></section>
  <section id="security" className="mx-auto grid max-w-7xl gap-8 px-5 py-24 md:grid-cols-3">{[[LockKeyhole,"Private by default","Your documents stay encrypted and access is deliberate."],[UsersRound,"Made to agree","Give every request an owner and every approval a clear record."],[Globe2,"Fits your stack","Bring your ledger. Bring your bank. Keep your source of truth."]].map(([Icon,title,copy]) => { const IconComponent = Icon as typeof LockKeyhole; return <article key={title as string}><IconComponent className="h-6 w-6 text-emerald-700"/><h3 className="mt-5 text-lg font-bold">{title as string}</h3><p className="mt-2 leading-7 text-stone-600">{copy as string}</p></article>})}</section>
  <section className="border-t border-stone-200 px-5 py-24 text-center"><p className="font-semibold text-emerald-700">Make the invisible work visible.</p><h2 className="mx-auto mt-4 max-w-2xl font-display text-5xl font-bold tracking-tight">A calmer way to move money&apos;s paperwork.</h2><div className="mt-8"><Button>Start free</Button></div></section>
  </main></div> }

function PlatformDashboard() { return <div className="rounded-2xl border border-slate-200 bg-white p-3 shadow-[0_24px_70px_rgba(37,99,235,.15)] sm:p-5"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div className="flex items-center gap-2"><BiteMark className="h-5 w-5"/><span className="text-sm font-bold">Northstar Group</span></div><BellRing className="h-4 w-4 text-slate-400"/></div><div className="grid gap-5 pt-5 sm:grid-cols-[.7fr_1.3fr]"><aside className="rounded-xl bg-slate-950 p-4 text-slate-200"><p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Financial ops</p>{[[BarChart3,"Overview"],[FileCheck2,"Payables", "12"],[Split,"Approvals", "4"],[LineChart,"Reporting"]].map(([Icon,name,badge]) => { const IconComponent = Icon as typeof BarChart3; return <div key={name as string} className={`mt-3 flex items-center gap-2 rounded-md px-2 py-2 text-xs ${name === "Payables" ? "bg-white/10 text-white" : "text-slate-400"}`}><IconComponent className="h-3.5 w-3.5"/><span>{name as string}</span>{badge && <b className="ml-auto text-emerald-300">{badge as string}</b>}</div>})}</aside><div><div className="flex justify-between"><div><p className="text-xs text-slate-500">Cash out this month</p><p className="mt-1 text-2xl font-bold tracking-tight">£248,560</p></div><span className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">↓ 12% vs last month</span></div><div className="mt-5 flex h-28 items-end gap-2">{[45,70,38,85,58,64,91,74,96,68,86,76].map((h,i) => <span key={i} className={`flex-1 rounded-t-sm ${i > 8 ? "bg-emerald-500" : "bg-blue-100"}`} style={{ height: `${h}%` }} />)}</div><div className="mt-5 grid grid-cols-3 gap-2">{[["8","need attention"],["31","ready to post"],["100%","audit linked"]].map(([value,label]) => <div key={label} className="rounded-lg bg-slate-50 p-2.5"><b className="block text-sm">{value}</b><span className="mt-1 block text-[10px] text-slate-500">{label}</span></div>)}</div></div></div></div> }

function VariantC() { return <div className="min-h-screen bg-white text-slate-950"><main><section className="relative overflow-hidden border-y border-slate-100 bg-[linear-gradient(115deg,#f8fbff_0%,#f2f7ff_60%,#effbf6_100%)]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><div><p className="inline-flex items-center gap-2 rounded-full bg-blue-100 px-3 py-1.5 text-xs font-bold text-blue-800"><WandSparkles className="h-3.5 w-3.5"/> The financial operations platform</p><h1 className="mt-6 max-w-2xl font-display text-5xl font-extrabold leading-[.98] tracking-[-.055em] sm:text-7xl">The system behind finance&apos;s best work.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">Automate the routine. Put controls where work happens. Give everyone—from AP clerk to CFO—the same confident view forward.</p><div className="mt-9 flex flex-wrap gap-3"><Button>Build your workflow</Button><Button secondary>Explore the platform</Button></div><div className="mt-12 flex flex-wrap gap-7"><Stat value="30 hrs" label="saved per close"/><Stat value="3×" label="faster approvals"/><Stat value="100%" label="traceable decisions"/></div></div><PlatformDashboard /></div></section>
  <section id="product" className="mx-auto max-w-7xl px-5 py-24"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-700">One platform. Different jobs.</p><h2 className="mt-4 font-display text-4xl font-bold tracking-tight sm:text-5xl">A complete picture, without a bigger pile of tools.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-3">{[[Layers3,"Document operations","Capture and organize everything finance touches."],[Zap,"Intelligent controls","Stop risk before it hits the ledger."],[LineChart,"Spend visibility","See what is committed, approved and waiting."]].map(([Icon,title,copy]) => { const IconComponent = Icon as typeof Layers3; return <article key={title as string} className="group rounded-2xl border border-slate-200 p-7 transition hover:border-blue-300 hover:shadow-xl hover:shadow-blue-100/50"><IconComponent className="h-7 w-7 text-blue-600"/><h3 className="mt-12 text-xl font-bold">{title as string}</h3><p className="mt-3 leading-7 text-slate-600">{copy as string}</p><a href="#solutions" className="mt-7 inline-flex items-center gap-1 text-sm font-bold text-blue-700">Explore <ChevronRight className="h-4 w-4"/></a></article>})}</div></section>
  <section id="solutions" className="bg-slate-950 px-5 py-24 text-white"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.78fr_1.22fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Built for how finance actually works</p><h2 className="mt-4 font-display text-4xl font-bold tracking-tight">A workflow for every important exception.</h2><p className="mt-5 leading-7 text-slate-400">Automation handles the normal. Your people have a focused place to make the judgment calls.</p><a href="#security" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-emerald-300">See how controls work <ArrowRight className="h-4 w-4"/></a></div><div className="grid gap-3 sm:grid-cols-2">{[[TimerReset,"The close owner","Keep the month moving with a clear command center."],[Building2,"The controller","Set guardrails across entities, teams and approval limits."],[Bot,"The AP team","Clear the queue with fast, explainable assistance."],[UsersRound,"The business","Approve in context, without being sent on a scavenger hunt."]].map(([Icon,title,copy]) => { const IconComponent = Icon as typeof TimerReset; return <article key={title as string} className="rounded-xl border border-slate-800 bg-slate-900 p-6"><IconComponent className="h-5 w-5 text-emerald-400"/><h3 className="mt-8 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{copy as string}</p></article>})}</div></div></div></section>
  <section id="security" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[1fr_.9fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-700">Confidence by design</p><h2 className="mt-4 max-w-2xl font-display text-4xl font-bold tracking-tight">Automation is only useful when it earns your trust.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">DocuBite keeps the evidence, policy and human decision close to the transaction—so speed never comes at the cost of control.</p><div className="mt-8 flex flex-wrap gap-x-8 gap-y-4 text-sm font-semibold text-slate-700">{["Evidence-first records", "Role-based workflows", "Supplier-aware checks", "Always-ready audit trail"].map(item => <span key={item} className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-600"/>{item}</span>)}</div></div><div className="rounded-2xl border border-blue-100 bg-blue-50 p-8"><LockKeyhole className="h-8 w-8 text-blue-700"/><p className="mt-16 text-sm font-semibold text-blue-800">“We finally have a consistent way to make the simple things fast—and the complex things safe.”</p><p className="mt-5 text-sm text-slate-600">Financial controller, multi-entity services group</p></div></section>
  <section id="resources" className="bg-emerald-500 px-5 py-24 text-center text-slate-950"><p className="text-sm font-bold">Your finance system can do more of the work.</p><h2 className="mx-auto mt-4 max-w-3xl font-display text-5xl font-extrabold tracking-tight">Bring clarity to every transaction.</h2><div className="mt-8"><Link href="/signup" className="inline-flex h-11 items-center gap-2 rounded-lg bg-slate-950 px-5 text-sm font-bold text-white">Start free <ArrowRight className="h-4 w-4"/></Link></div></section>
  </main></div> }

export function LandingPagePrototype({ variant }: { variant: Variant }) {
  return <><div className="-mx-0">{variant === "a" ? <VariantA /> : variant === "b" ? <VariantB /> : <VariantC />}</div><LandingSwitcher current={variant} /></>
}
