import type { PaymentInstruction } from "@/lib/payments/za-eft-csv"

/** Plain-text remittance advice for one supplier, listing every invoice covered by the payment.
 * Kept as text (not PDF) for now — the AP repositioning plan intentionally scopes payment work to
 * preparation-only, and a text advice pasted into an email or attached as .txt covers 90% of the
 * cases a small AP team hits. PDF generation is a future concern.
 *
 * Groups instructions by supplier so a payment run covering N invoices for one supplier renders
 * as ONE advice (with a line per invoice), not N separate advices. */

export type RemittanceAdvice = {
  supplier: string
  currencyCode: string
  totalAmount: number
  invoices: Array<{ reference: string; amount: number }>
  /** #347: a claim's advice never mixes with a bill's — Bill Pay never lets a bill and a claim
   * share one `supplier`/payee string, so every group in `buildRemittanceAdvices` is one kind. */
  kind: "bill" | "claim"
  text: string
}

export function buildRemittanceAdvices(instructions: PaymentInstruction[], payer: { name: string; runDate: Date }): RemittanceAdvice[] {
  const bySupplier = new Map<string, PaymentInstruction[]>()
  for (const ins of instructions) {
    const list = bySupplier.get(ins.supplier) ?? []
    list.push(ins)
    bySupplier.set(ins.supplier, list)
  }

  const advices: RemittanceAdvice[] = []
  for (const [supplier, group] of bySupplier) {
    // Split by currency too — one advice per (supplier, currency) so totals never mix.
    const byCurrency = new Map<string, PaymentInstruction[]>()
    for (const ins of group) {
      const list = byCurrency.get(ins.currencyCode.toUpperCase()) ?? []
      list.push(ins)
      byCurrency.set(ins.currencyCode.toUpperCase(), list)
    }
    for (const [currencyCode, rows] of byCurrency) {
      const totalAmount = rows.reduce((sum, r) => sum + r.amount, 0)
      const invoices = rows.map((r) => ({ reference: r.reference, amount: r.amount }))
      const kind: "bill" | "claim" = rows[0].expenseClaimId ? "claim" : "bill"
      const text = renderRemittanceText({ supplier, currencyCode, totalAmount, invoices, kind, payer })
      advices.push({ supplier, currencyCode, totalAmount, invoices, kind, text })
    }
  }
  return advices
}

function renderRemittanceText(input: {
  supplier: string
  currencyCode: string
  totalAmount: number
  invoices: Array<{ reference: string; amount: number }>
  kind: "bill" | "claim"
  payer: { name: string; runDate: Date }
}): string {
  const date = input.payer.runDate.toISOString().slice(0, 10)
  const rows = input.invoices
    .map((inv) => `  ${inv.reference.padEnd(20)}  ${input.currencyCode} ${inv.amount.toFixed(2).padStart(12)}`)
    .join("\n")
  const noun = input.kind === "claim" ? "reimbursement claim" : "invoices"
  return [
    `Remittance advice`,
    ``,
    `From:  ${input.payer.name}`,
    `To:    ${input.supplier}`,
    `Date:  ${date}`,
    ``,
    `Payment for the following ${noun} has been processed to your bank account:`,
    ``,
    rows,
    ``,
    `  ${"TOTAL".padEnd(20)}  ${input.currencyCode} ${input.totalAmount.toFixed(2).padStart(12)}`,
    ``,
    `Reference: ${input.invoices.map((i) => i.reference).join(", ")}`,
    ``,
    `This advice was generated by DocuBite. If you did not receive payment within 3 working`,
    `days of this date, please reply to this email.`,
  ].join("\n")
}
