import { prisma } from "@/lib/db"
const ws = "af91555d-7450-4b21-a8ac-73db092617c8"
const m = await prisma.workspaceMember.findFirst({ where: { workspaceId: ws, userId: "00000000-0000-4000-8000-00000000d0de" } })
console.log("membership", m)
const allMembers = await prisma.workspaceMember.findMany({ where: { workspaceId: ws } })
console.log("all members", allMembers)
const task = await prisma.reviewTask.findFirst({ where: { workspaceId: ws, documentId: "ecc8bced-51db-4e66-b9b5-7baea720ba21" }, orderBy: { createdAt: "desc" } })
console.log("latest review task for pending doc", task)
const pendingDoc = await prisma.document.findUnique({ where: { id: "ecc8bced-51db-4e66-b9b5-7baea720ba21" }, select: { status: true, codingData: true } })
console.log("pending doc now", pendingDoc)
const rule = await prisma.supplierAccountRule.findFirst({ where: { workspaceId: ws, supplierName: { contains: "Acme" } } })
console.log("rule", rule)
const devUser = await prisma.user.findFirst({ where: { email: "dev@docubite.local" } })
console.log("devUser", devUser)
console.log("rule", rule)
const conn = await prisma.integrationConnection.findFirst({ where: { workspaceId: ws, provider: "quickbooks" } })
console.log("connection", conn)
const docs = await prisma.document.findMany({ where: { workspaceId: ws, status: "reviewed" }, select: { id: true, filename: true, codingData: true, receivedAt: true } })
console.log("reviewed docs", JSON.stringify(docs, null, 2))
await prisma.$disconnect()
