#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# Meta's App Dashboard / Business Manager UI moves around; the paths below are
# the ones current at time of writing. If a menu is missing, use the search box
# in the top bar of the dashboard.

TOTAL_STAGES=8

banner "DocuBite · WhatsApp intake provisioning"

# ── 1. Meta app ───────────────────────────────────────────────────────────
stage "Meta app with the WhatsApp product"
say "DocuBite needs one Meta app (type: Business) with WhatsApp added to it."
open_url "https://developers.facebook.com/apps/"
step "If you already have the app, open it. Otherwise: Create App → use case 'Other' →"
step "  type 'Business' → pick your Business Portfolio → Create."
step "In the app's left nav: Add product → WhatsApp → Set up."
step "Copy the App ID from the top bar (only used to build links below)."
note "Docs: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started"
ask WHATSAPP_META_APP_ID "Paste the App ID:"
write_env WHATSAPP_META_APP_ID "$WHATSAPP_META_APP_ID"

# ── 2. App secret ─────────────────────────────────────────────────────────
stage "App secret (webhook signature)"
say "The route HMAC-checks every webhook body with this. Never share it."
open_url "https://developers.facebook.com/apps/${WHATSAPP_META_APP_ID}/settings/basic/"
step "App settings → Basic → App secret → Show (re-enter your password) → copy."
note "Docs: https://developers.facebook.com/docs/graph-api/webhooks/getting-started#verification-requests"
ask_secret WHATSAPP_APP_SECRET "Paste the App secret:"
write_env WHATSAPP_APP_SECRET "$WHATSAPP_APP_SECRET"

# ── 3. Phone number ───────────────────────────────────────────────────────
stage "Phone number ID and business number"
say "DocuBite needs Meta's internal id for the number (outbound calls) and the"
say "human-facing number itself (shown in Admin › Configuration › Intake)."
open_url "https://developers.facebook.com/apps/${WHATSAPP_META_APP_ID}/whatsapp-business/wa-dev-console/"
step "WhatsApp → API Setup. In the 'From' dropdown pick your number."
note "For production, first add a real number: WhatsApp → API Setup → 'Add phone number'"
note "(needs a number that can receive an SMS/voice OTP and is not on personal WhatsApp)."
note "The Meta test number works for a trial but only messages up to 5 verified recipients."
step "Copy 'Phone number ID' (a long integer, NOT the WhatsApp Business Account ID)."
note "Docs: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started#set-up-developer-assets"
note "Add a number: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started/add-a-phone-number"
ask WHATSAPP_PHONE_NUMBER_ID "Paste the Phone number ID:"
step "Copy the displayed phone number itself, in E.164 form (e.g. +27821234567)."
ask WHATSAPP_BUSINESS_NUMBER "Paste the business number (E.164):"
write_env WHATSAPP_PHONE_NUMBER_ID "$WHATSAPP_PHONE_NUMBER_ID"
write_env WHATSAPP_BUSINESS_NUMBER "$WHATSAPP_BUSINESS_NUMBER"

# ── 4. Permanent access token ─────────────────────────────────────────────
stage "Permanent System User access token"
say "The token on the API Setup page expires in 24h. Production needs a"
say "System User token from Business Manager, which never expires."
open_url "https://business.facebook.com/settings/system-users"
step "Business settings → Users → System users → Add → name it 'docubite-whatsapp',"
step "  role Admin → Create."
step "Select it → 'Add assets' → Apps → tick your app → enable 'Manage app' → Save."
step "Also 'Add assets' → WhatsApp accounts → tick your WABA → 'Manage' → Save."
step "Click 'Generate new token' → pick the app → expiration 'Never' →"
step "  tick permissions: whatsapp_business_messaging, whatsapp_business_management → Generate."
step "Copy the token now; Meta will not show it again."
note "Docs: https://developers.facebook.com/docs/whatsapp/business-management-api/get-started#system-user-access-tokens"
ask_secret WHATSAPP_ACCESS_TOKEN "Paste the System User token:"
write_env WHATSAPP_ACCESS_TOKEN "$WHATSAPP_ACCESS_TOKEN"

# ── 5. Verify token ───────────────────────────────────────────────────────
stage "Webhook verify token"
say "A shared secret YOU choose. Meta echoes it in the GET handshake; DocuBite"
say "compares it to WHATSAPP_VERIFY_TOKEN. Distinct from the app secret."
if generated=$(openssl rand -hex 24 2>/dev/null); then
  note "Generated one for you: $generated"
  note "Press Enter to accept it, or paste your own."
  ask_secret WHATSAPP_VERIFY_TOKEN "Verify token:"
  [[ -z "$WHATSAPP_VERIFY_TOKEN" ]] && WHATSAPP_VERIFY_TOKEN="$generated"
else
  ask_secret WHATSAPP_VERIFY_TOKEN "Choose a verify token (random, 20+ chars):"
fi
write_env WHATSAPP_VERIFY_TOKEN "$WHATSAPP_VERIFY_TOKEN"

# ── 6. Deploy ─────────────────────────────────────────────────────────────
stage "Deploy the env vars to production"
say "config.whatsapp.enabled only turns on when ALL of these are set on the running"
say "container: WHATSAPP_APP_SECRET, WHATSAPP_VERIFY_TOKEN, WHATSAPP_PHONE_NUMBER_ID,"
say "WHATSAPP_ACCESS_TOKEN (+ WHATSAPP_BUSINESS_NUMBER for the UI)."
say "They are now in $ENV_FILE. In another terminal, push them to Lightsail and redeploy:"
say "  ./scripts/set-whatsapp-env.sh $ENV_FILE"
say "  ./scripts/vps-ssh.sh 'cd ~/docubite && git pull && ./scripts/deploy.sh'"
WHATSAPP_PUBLIC_BASE_URL="${WHATSAPP_PUBLIC_BASE_URL:-https://docubite.app}"
ask WHATSAPP_PUBLIC_BASE_URL "Public HTTPS base URL [https://docubite.app]:"
WHATSAPP_PUBLIC_BASE_URL="${WHATSAPP_PUBLIC_BASE_URL:-https://docubite.app}"
WHATSAPP_PUBLIC_BASE_URL="${WHATSAPP_PUBLIC_BASE_URL%/}"
WEBHOOK_URL="${WHATSAPP_PUBLIC_BASE_URL}/api/inbound-whatsapp"
pause "Press Enter once the app is redeployed with the new env vars."
say "Checking the handshake at $WEBHOOK_URL ..."
if command -v curl >/dev/null 2>&1; then
  reply=$(curl -fsS --max-time 15 "${WEBHOOK_URL}?hub.mode=subscribe&hub.verify_token=${WHATSAPP_VERIFY_TOKEN}&hub.challenge=docubite-check" 2>/dev/null || true)
  if [[ "$reply" == "docubite-check" ]]; then
    printf '  %s✓ handshake OK%s — the route is live and the verify token matches\n' "$GREEN" "$RESET"
  else
    warn "handshake did not echo the challenge (got: '${reply:-<no response>}')."
    warn "503 = env vars not loaded; 403 = verify token mismatch. Fix, redeploy, re-run."
    SKIPPED+=("Handshake failed at $WEBHOOK_URL: fix env/deploy, then re-run this wizard")
  fi
else
  warn "curl not found; skipped the handshake check."
fi

# ── 7. Webhook subscription ───────────────────────────────────────────────
stage "Subscribe Meta's webhook to DocuBite"
open_url "https://developers.facebook.com/apps/${WHATSAPP_META_APP_ID}/whatsapp-business/wa-settings/"
step "WhatsApp → Configuration → Webhook → Edit."
say "  Callback URL:  $WEBHOOK_URL"
say "  Verify token:  (the one from stage 5, now in $ENV_FILE as WHATSAPP_VERIFY_TOKEN)"
step "Click 'Verify and save'. Meta will GET the URL; it must succeed."
step "Under 'Webhook fields', click Manage → Subscribe to 'messages' → Done."
note "Docs: https://developers.facebook.com/docs/whatsapp/cloud-api/guides/set-up-webhooks"
pause "Press Enter once 'messages' shows as subscribed."

# ── 8. End-to-end test ────────────────────────────────────────────────────
stage "Send a real receipt"
say "Final check that a photo lands in the Receipts queue."
step "In DocuBite: Admin › Configuration › Intake → Allowed senders → add YOUR phone"
step "  number (E.164) with a label."
note "If you're on Meta's test number, also add your phone under API Setup → 'To' →"
note "'Manage phone number list' and accept the WhatsApp invite it sends."
step "From that phone, WhatsApp a photo of any receipt to $WHATSAPP_BUSINESS_NUMBER."
say "Expected: a 'Got it — 1 receipt added…' reply and a new row in the Receipts queue."
if ! confirm "Did the reply arrive and the receipt appear?"; then
  SKIPPED+=("End-to-end test failed: check Intake log in Admin › Configuration › Intake and the app logs for '[inbound-whatsapp]'")
fi

finish
